options.go

Fixes https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/25

fix: specify scope for WithCredentialsFile/JSON

---

dialer_test.go
internal/alloydb/instance_test.go
internal/alloydb/refresh.go
internal/alloydbapi/client.go
internal/mock/alloydbadmin.go

feat: switch to Connect API and verify server name

---

internal/alloydb/refresh.go

Please provide a detailed description on what changes your PR will have.
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose) 
before writing your code!  That way we can discuss the change, evaluate 
designs, and agree on the general idea.
- Fixes #<issue_number_goes_here>

chore: fix comment in about refresh duration

---

.github/workflows/cover.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml

Add support for latest Go version.

feat: add support for Go 1.20

---

internal/alloydb/instance.go
internal/alloydb/instance_test.go

Updating refresh buffer to 4 minutes and fixing refresh logic.

fix: improve reliability of certificate refresh

---

internal/alloydb/instance.go

This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/449.

chore: cleanup instance.go

---

README.md

Adding details for supported tracing and metrics.

docs: update README with supported metrics and traces

---

.github/workflows/cover.yaml
.github/workflows/labels.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml

ci: update workflows to read-only and pin shas

---

metrics_test.go

chore: increase timeout for metric collection

---

doc.go

chore: add basic usage to godoc

---

dialer.go
dialer_test.go
options.go

feat: add support for WithOneOffDialFunc (#361)

---

.github/workflows/tests.yaml
database_sql_test.go
direct_database_sql_test.go
direct_pgxpool_test.go
e2e_test.go
pgxpool_test.go

docs: add test demonstrating Auto IAM AuthN on direct path

---

internal/alloydb/refresh.go
internal/mock/alloydbadmin.go

chore: prefer public key in API requests

---

dialer.go
internal/alloydb/instance.go

chore: introduce interface for alloydb.Instance

---

dialer.go
dialer_test.go

This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/686

fix: ensure cert refresh recovers from computer sleep

---

README.md

docs: add IAM Authn details

---

pgxpool_test.go

docs: use pgxv5 in pgxpool sample

---

database_sql_public_ip_test.go
e2e_test.go
pgxpool_public_ip_test.go

docs: add region tags for public IP

---

README.md
debug/debug.go
dialer.go
internal/alloydb/instance.go
internal/alloydb/instance_test.go
internal/alloydb/refresh.go
options.go

This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/726.
Fixes #506

feat: add support for debug logging

---

.github/workflows/tests.yaml

Related to https://github.com/actions/runner/issues/2708.

chore: report disk usage on test run

---

internal/alloydb/instance_test.go

In some cases, the refresh ahead cache may have already begun a refresh cycle before the test calls Close on the instance. When this happens, the returned error is not a context.Canceled error, but instead a DialError.
This commit updates the TestClose method to check that either error is returned. The point of the test is to ensure close results in an error when the next call to ConnectionInfo is made. Which error is less important.
Fixes #444

chore: resolve race condition in test assertion

---

.github/renovate.json5
.github/workflows/codeql.yml
.github/workflows/cover.yaml
.github/workflows/govulncheck.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml
go.mod
go.sum

feat: add support for Go 1.23

---

.github/ISSUE_TEMPLATE/feature_request.yaml
.github/workflows/scorecard.yml
internal/trace/metrics.go

Thanks for the project, I love it.
During code review, I fixed minor typo/grammar along the way.

chore: correct a few typos

---

errtype/errors.go
errtype/errors_test.go

See https://google.github.io/styleguide/go/decisions.html#error-strings.

chore: use lowercase for all errors

---

dialer.go

Fixes #684 - a port of the same change in CloudSQL's https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/983. Small difference here is opting to use `(*atomic.Int64) Add` and `(*atomic.Int64) Swap` instead to avoid bugs with 32-bit platforms ([ref](https://pkg.go.dev/sync/atomic#pkg-note-BUG))

fix: reduce the number of memory allocations and latency overhead
