internal/alloydb/instance.go
This fixes the `panic: unaligned 64-bit atomic operation` error on 386 architectures.
[bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose) 
before writing your code!  That way we can discuss the change, evaluate 
designs, and agree on the general idea.
- Fixes https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/27
=> fix: adjust alignment for 32-bit arch

.github/workflows/tests.yaml
Run unit tests on 32-bit Linux and Windows with latest Go version. Need to merge https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/33 first
fixes: #30
=> chore(ci): add unit tests for 32-bit linux and windows

internal/mock/alloydbadmin.go
Also, remove log line that was causing a race condition.
=> chore: close listener after context cancellation

connect_tls_117.go, connect_tls_other.go, dialer.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/427.
=> feat: use handshake context when possible

dialer.go, internal/alloydb/instance.go, internal/alloydb/instance_test.go, internal/alloydb/refresh.go, internal/alloydb/refresh_test.go, options.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/458.
=> fix: prevent repeated context expired errors

dialer_test.go, internal/alloydb/refresh.go, internal/mock/alloydb.go
Manual verify is no more needed since server certificates now support SAN (instance IP address). Parsing of client cert is needed to capture the expiry time.
=> feat: use instance IP as SAN

internal/alloydb/refresh.go
This is more of documentation change, as the server only supports TLS 1.3.
=> fix: require TLS 1.3 always

internal/trace/metrics.go, metrics_test.go
This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/393.
Fixes #311.
=> fix: remove leading slash from metric names

dialer.go, dialer_test.go
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/550
=> fix: stop background refresh for bad instances

.github/workflows/tests.yaml
Integration runs on latest Go version on Linux. Units run on min and max supported Go versions on Linux, Windows, and macOS. We don't have integration test support for multiple OSes, so we lean on unit tests there.
=> chore: pare down test size

internal/alloydb/refresh.go, internal/mock/alloydbadmin.go
Reverts GoogleCloudPlatform/alloydb-go-connector#401
We should continue to use pem CSR for `v1beta` endpoint. Planning to move to public key and `v1` endpoint soon.
=> Revert "chore: prefer public key in API requests"

internal/alloydb/refresh.go, internal/mock/alloydbadmin.go
Instead of extracting the CA cert from `PemCertificateChain[2]` ourselves which is prone to potential errors in the future if the API changes, we should instead use the `CaCert` field of the response body and let the API handle the work of extracting it.
=> chore: use CaCert from resp body

internal/alloydb/instance.go, internal/alloydb/instance_test.go
Hello, 
I discovered that closing the instance will cause an infinite loop in the `scheduleRefresh` function. 
Closing the Instance will cancel the context, which causes an error in the Limiter:
https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/ff5ca3575f176fb165d212e6b55e898201e9a3f2/internal/alloydb/instance.go#L263-L267
Every error here will trigger a new refresh with 0 sec delay:
https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/ff5ca3575f176fb165d212e6b55e898201e9a3f2/internal/alloydb/instance.go#L283-L286
This refresh will also fail because of the canceled context.
The result is high resource consumption, once the instance has been closed, because of this infinite loop.
As a fix I propose to check the context earlier and don't schedule a new refresh …
=> fix: avoid scheduling an instance refresh if the context is done

README.md, dialer.go, dialer_test.go, e2e_test.go, internal/alloydb/instance.go, internal/alloydb/instance_test.go, internal/alloydb/refresh.go, internal/alloydb/refresh_test.go, internal/mock/alloydb.go, internal/mock/alloydbadmin.go, metrics_test.go, options.go
Add support for Public IP connections to AlloyDB instances via Go Connector. Default  option for `ipType` will be Private IP but users wishing to use Public IP can use the new `WithPublicIP()` DialOption.
PR Checklist:
=> feat: add support for public IP

README.md
We received feedback from customers indicating confusion regarding the usage of `AlloyDB Admin API` in our documentation. To address this, we are updating the API reference to `AlloyDB API`, as recommended in the [official documentation](https://cloud.google.com/alloydb/docs/reference/rest).
=> docs: Use AlloyDB API for consistency with the official documentation.

go.mod, go.sum
This dependency is used in test only, but it's causing govulncheck to fail. Upgrading it to resolve the warning.
=> deps: upgrade to latest protobuf version

dialer.go, internal/alloydb/refresh.go, internal/alloydb/refresh_test.go
When we added a check to validate certificates on all new connections
[1], we also inadverantly caused each connection to trigger a duplicate
and blocking refresh operation with the following lines:
if c.Certificates[0].Leaf == nil {
return true
}
When the tls.Config is created in refresh.go, it configures a client
certificate chain and adds the CA cert as a Root CA. However, the client
certificate chian is created with tls.X509KeyPair which explicitly
states:
"On successful return, Certificate.Leaf will be nil because the parsed
form of the certificate is not retained." [2]
As a result, the nil check above was always triggered and thereby
causing a duplicate refresh operation. An immediate fix to this
situation is to set the leaf certificate, which is what this commit
does. In fact, …
=> fix: remove duplicate refresh for all connections

dialer.go, dialer_test.go, internal/alloydb/instance.go, internal/alloydb/instance_test.go, internal/alloydb/refresh.go, internal/alloydb/refresh_test.go
Rather than construct a tls.Config in the API client, this commit introduces a ConnectionInfo struct to hold all connection information including certificates, root CA certs, and expiration. Later those fields are used to construct a tls.Config type in the same function that establishes the TLS connection.
This change allows for easier configuration of server name values in the tls.Config and is in preparation for supporting PSC (which will use the PSC-based DNS name).
=> refactor: simplify internal interface

.github/workflows/tests.yaml, README.md, database_sql_public_ip_test.go, dialer.go, e2e_test.go, internal/alloydb/instance_test.go, internal/alloydb/refresh.go, internal/alloydb/refresh_test.go, internal/mock/alloydb.go, internal/mock/alloydbadmin.go, options.go, pgxpool_psc_test.go
This commit adds support for dialing a PSC endpoint with the Go Connector. Callers should provide the WithPSC DialOption to dial calls to send all traffic to the PSC endpoint.
=> feat: add support for PSC

.github/workflows/govulncheck.yaml
The workflow wasn't checking out the SHA of the PR. This commit corrects the error.
=> chore: fix govulncheck.yaml

README.md, database_sql_public_ip_test.go, dialer.go, dialer_test.go
If the dialer has already been closed, return a clear error.
Fixes #522
=> fix: return a friendly error if the dialer is closed

README.md
Fix pgx version for README because the example code uses pgxv5 instead of pgxv4.
=> docs: fix pgx version for README

dialer.go, dialer_test.go, internal/alloydb/instance.go
This commit moves connection tracking to the dialer and reduces the size of the connectionInfoCache interface. This change makes it easier to implement alternate caches (e.g., a lazy refresh cache). In addition, this commit renames some variables to match the new names.
=> refactor: shrink connectionInfoCache interface

dialer.go, dialer_test.go
When a caller requests an IP type not in the cache, the dialer will now invalidate the cached connection info. This ensures the dialer will have an up-to-date cache for subsequent requests.
Fixes #554
=> feat: invalidate cache on IP type errors

dialer.go, internal/alloydb/lazy.go, internal/alloydb/lazy_test.go, internal/alloydb/refresh.go, options.go
When creating a Dialer with the WithLazyRefresh option, the connection info and ephemeral certificate will be refreshed only when the cache certificate has expired. No background goroutines run with this option, making it ideal for use in Cloud Run and other serverless environments where the CPU may be throttled.
This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/772
Fixes #549
=> feat: add support for a lazy refresh

dialer.go, dialer_test.go, internal/alloydb/instance.go, internal/alloydb/refresh.go, internal/alloydb/static.go, internal/mock/alloydb.go, internal/mock/alloydbadmin.go, options.go
In development environments it can be useful to seed the Dialer with
static connection info properties. This commit makes it possible to
replace the internal lazy or refresh ahead cache with a static cache
that is populated from JSON data.
The JSON format looks like this:
```
{
"publicKey": "<PEM Encoded public RSA key>",
"privateKey": "<PEM Encoded private RSA key>",
"projects/<PROJECT>/locations/<REGION>/clusters/<CLUSTER>/instances/<INSTANCE>": {
"ipAddress": "<PSA-based private IP address>",
"publicIpAddress": "<public IP address>",
"pscInstanceConfig": {
"pscDnsName": "<PSC DNS name>"
},
"pemCertificateChain": [
"<client cert>", "<intermediate cert>", "<CA cert>"
],
"caCert": "<CA cert>"
}
}
```
=> feat: support static connection info

README.md, debug/debug.go, dialer.go, internal/alloydb/instance.go, internal/alloydb/instance_test.go, internal/alloydb/lazy.go, internal/alloydb/static.go, options.go
Callers may now provide a context to correlate logs with trace IDs in their implementation of the interface.
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/797
=> feat: add context debug logger

.github/renovate.json5
matchManagers works as see in the AlloyDB Auth Proxy.
=> chore: correct renovate's go grouping

dialer.go, key_gen_test.go
When lazy refresh is enabled, the RSA key generation will not occur until a client calls Dial. This change helps cold start times in serverless environments.
Prior to this commit, the RSA key generation was done at the package level using globals. This commit removes the use of globals and moves the key generation into the dialer. This means multiple dialers will now have multiple RSA keys. Before this commit, multiple dialers all shared the same RSA key. If this is a concern, callers may still configure their own RSA key across multiple dialers.
Fixes #584
=> feat: generate RSA key lazily for lazy refresh

dialer.go
The PSC DNS name is included in all existing server certificates. So now we can use the PSC DNS name to verify the certificate instead of the private IP address of the instance. Users of PSC-enabled clusters won't have access to the private IP address anyway.
Fixes #546
=> fix: rely on the PSC DNS name instead of the private IP address

.github/workflows/codeql.yml, .github/workflows/cover.yaml, .github/workflows/govulncheck.yaml, .github/workflows/lint.yaml, .github/workflows/tests.yaml
The custom runner persists between runs and as a result never cleans up Go modules. As a result, the Go mod cache grows and grows and grows, which eventually results in out of disk space errors. Rather than keep bumping the disk size, this PR disables the cache such that a test run doesn't leave a big footprint behind.
Related to https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/696
=> chore: resolve out of disk space errors

dialer.go, dialer_test.go, e2e_test.go, internal/alloydb/instance.go, internal/alloydb/instance_test.go, internal/alloydb/lazy.go, internal/alloydb/lazy_test.go, internal/alloydb/refresh.go, internal/alloydb/refresh_test.go, options.go, pgxpool_test.go
This commit adds an option (marked for internal usage only) that will allow clients to disable the metadata exchange. Future versions will make this option a no-op once all internal consumers are able to use the metadata exchange without incompatible behavior with VPC-SC.
=> chore: add option for connection check opt-out

dialer_test.go
This commit removes a low-value assertion whose sole intention was to validate context propagation.
Fixes #593
=> chore: remove flaky assertion

README.md, dialer.go, internal/trace/metrics.go, metrics_test.go
Port of CloudSQL's https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/856
Fixes https://github.com/GoogleCloudPlatform/alloydb-go-connector/issues/607
=> feat: add bytes_sent and bytes_received as metrics

dialer.go, internal/alloydb/refresh.go, internal/tel/doc.go, internal/tel/metrics.go, internal/tel/metrics_test.go, internal/tel/trace.go
Before introducing OpenTelemetry into this project, it's important to have a clear distinction between the existing telemetry based on OpenCensus and the new telemetry which will be based on OpenTelemetry. To do that, this commit renames the existing package containing metrics and tracing to be more generic. Later commits will introduce a "tel/v2" to make the relationship between old and new clear.
=> refactor: rename internal trace package to tel

.github/renovate.json5, .github/workflows/tests.yaml, go.mod
Google Cloud Go now follows the official Go support version policy. This commit updates our test infrastructure to match.
=> feat: match official Go version support policy

.github/renovate.json5, .github/workflows/codeql.yml, .github/workflows/cover.yaml, .github/workflows/govulncheck.yaml, .github/workflows/lint.yaml, .github/workflows/tests.yaml, go.mod
Go 1.22 has reach EOL, see https://endoflife.date/go. 
Go 1.24 has been released, see https://go.dev/doc/go1.24.
Fixes #655
=> feat: add support for Go 1.24 and drop Go 1.22

database_sql_public_ip_test.go, database_sql_test.go, dialer.go, dialer_test.go, e2e_test.go, internal/alloydb/instance.go, internal/alloydb/instance_test.go, internal/alloydb/lazy.go, internal/alloydb/lazy_test.go, internal/tel/v2/tel.go, metrics_test.go, options.go, pgxpool_psc_test.go, pgxpool_public_ip_test.go
This commit does two things:
1. It configures the alloydbconn internals to send telemetry to AlloyDB
reporting on the library's performance (e.g., dial count, refresh
count, bytes tx and rx)
1. It allows callers to disable this internal telemetry.
Presently, the telemetry is not publicly readable. It is put in place in
this commit as a steel thread for improving the performance,
reliability, and diagnostics for the connector.
Future work will surface these system metrics alongside other AlloyDB
metrics for callers to use as they see fit. Unlike the existing
OpenCensus based implementation which uses custom metrics (paid for by
the caller), this implementation uses OpenTelemetry for system metrics
(paid for by AlloyDB).
=> feat: allow for disabling built-in metrics

dialer.go, dialer_test.go, internal/tel/v2/tel.go
The internal metrics use an exporter and a provider. Previously, when calling Close on the alloydbconn.Dialer, the code would shut down the provider and the exporter. Meanwhile, the provider also tries to shut down the exporter, leading to cases where the exporter's shutdown method was called twice.
This commit updates the Shutdown method on the internal metric reporter to shutdown only the provider (which shuts down the exporter). In addition, since internal metric shutdown errors are unactionable, this commit changes the Close method on the Dialer to log the error when debug logging is enabled and otherwise not surface it to callers.
Fixes GoogleCloudPlatform/alloydb-auth-proxy/issues/776
=> fix: shut down the internal exporter only once

go.mod
Did not notice that https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/682 added back in the toolchain (oops!) which we don't need anymore. See https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/658#discussion_r1954947656, also re-verified it myself also using `go mod tidy`
=> deps: remove toolchain directive
